// Master chassis parts catalog
// Source: NS Chassis Parts Guide (5-23-2025)
// Job codes intentionally excluded.

const parts = [
  { category: "Automatic Slack Adjuster", partNumber: "HDX402-26211", description: "ABA KIT 5.5 IN 28 SPL W/STROKE" },
  { category: "Automatic Slack Adjuster", partNumber: "MOTMK41106S", description: "10 SPL AUTO 6 IN STR AUTO CHK" },
  { category: "Automatic Slack Adjuster", partNumber: "MOTMK42100S", description: "28 SPL AUTO 5.5 IN STR AUTO CHK" },
  { category: "Automatic Slack Adjuster", partNumber: "MOTMK42106S", description: "28 SPL AUTO 6 IN STR AUTO CHK" },
  { category: "Automatic Slack Adjuster", partNumber: "PROSA1140", description: "28 SPL AUTO 5.5 IN STR GUN" },
  { category: "Automatic Slack Adjuster", partNumber: "PROSA1141", description: "28 SPL AUTO 6 IN STR GUN" },
  { category: "Automatic Slack Adjuster", partNumber: "PROSA1149", description: "28 SPL AUTO 5.5 IN STR GUN" },
  { category: "Automatic Slack Adjuster", partNumber: "PROSA1150", description: "28 SPL AUTO 6 IN STR GUN" },
  { category: "Automatic Slack Adjuster", partNumber: "PROSA22102", description: "28 SPL 5.5 IN 6.5 IN STR CBI" },
  { category: "Automatic Slack Adjuster", partNumber: "PROSA55073", description: "28 SPL AUTO 5.5 IN STR MTR" },
  { category: "Automatic Slack Adjuster", partNumber: "PROSA56042", description: "10 SPL 6 IN STR .62-18 W/CLV" },
  { category: "Automatic Slack Adjuster", partNumber: "PROSA56074", description: "28 SPL AUTO 6 IN STR MTR" },
  { category: "Automatic Slack Adjuster", partNumber: "PROSA56212", description: "28 SPL AUTO 6 IN STR NO/CLV HDX" },
  { category: "Automatic Slack Adjuster", partNumber: "PROSA57041", description: "10 SPL 5.5 IN STR 5/8-18 W/CLV" },
  { category: "Automatic Slack Adjuster", partNumber: "TSE07135SX", description: "28 SPL 5.5 IN STR SASA OPT TSE" },

  { category: "Brake Cam Bushing and Seal", partNumber: "FRUACF4024-900", description: "S CAM BKT RETAINER KIT" },
  { category: "Brake Cam Bushing and Seal", partNumber: "HOL51830024", description: "S CAM KIT 1-5/8" },
  { category: "Brake Cam Bushing and Seal", partNumber: "MTRKIT8048", description: "S CAM BRKT KIT PRESS IN" },
  { category: "Brake Cam Bushing and Seal", partNumber: "PROWC8696HD", description: "S CAM BRKT" },
  { category: "Brake Cam Bushing and Seal", partNumber: "PROWC8714", description: "CAMSHAFT SUPPORT BRACKET LH/RH" },
  { category: "Brake Cam Bushing and Seal", partNumber: "PROWC8827", description: "S CAM WASHER 1-17/64 IN, 1-7/8 IN" },
  { category: "Brake Cam Bushing and Seal", partNumber: "PROWCR1442HD", description: "S BRKT KIT MERITOR W/BOLT ON" },

  { category: "Brake Chamber", partNumber: "HDXGC3030L", description: "BRK CHAMBER 3030 W/CLV" },
  { category: "Brake Chamber", partNumber: "TSE3030TLW3ULP8036", description: "3030 3 IN STROKE WELD CLEV NS" },
  { category: "Brake Chamber", partNumber: "TSE3030TVR2", description: "3030 2.5 IN STROKE OMNI VCT TSE-REX" },
  { category: "Brake Chamber", partNumber: "TSEK680-138", description: "KIT 6.80 IN L, FIXED 1.38 IN PIN SPC TREX" },

  { category: "S Cam", partNumber: "PROWC504L", description: "LH 28 SPL 17-5/16 IN LGTH, 1-1/2 IN DIA" },
  { category: "S Cam", partNumber: "PROWCQ352L", description: "LH 28 SPL 20-3/32 IN LGTH, 1-1/2 IN DIA" },
  { category: "S Cam", partNumber: "PROWC154L", description: "LH 28 SPL 20-3/8 IN LGTH, 1-1/2 IN DIA" },
  { category: "S Cam", partNumber: "HOL51830004", description: "LH 28 SPL 20-3/8 IN LGTH, 1-1/2 IN DIA" },
  { category: "S Cam", partNumber: "PROWC170L", description: "LH 28 SPL 20-3/8 IN LGTH, 1-1/2 IN DIA" },
  { category: "S Cam", partNumber: "PROWC528L", description: "LH 37 SPL 16-1/8 IN LGTH, 1-5/8 IN DIA" },
  { category: "S Cam", partNumber: "PROWC512L", description: "LH 37 SPL 21-1/8 IN LGTH, 1-5/8 IN DIA" },
  { category: "S Cam", partNumber: "PROWC507R", description: "RH 10 SPL 20-3/8 IN LGTH, 1-1/2 IN DIA" },
  { category: "S Cam", partNumber: "PROWC505R", description: "RH 28 SPL 17-5/16 IN LGTH, 1-1/2 IN DIA" },
  { category: "S Cam", partNumber: "HOL51830005", description: "RH 28 SPL 20-3/8 IN LGTH, 1-1/2 IN DIA" },
  { category: "S Cam", partNumber: "PROWC171R", description: "RH 28 SPL 20-3/8 IN LGTH, 1-1/2 IN DIA" },
  { category: "S Cam", partNumber: "PROWC155R", description: "RH 28 SPL 20-3/8 IN LGTH, 1-1/2 IN DIA" },
  { category: "S Cam", partNumber: "PROWC529R", description: "RH 37 SPL 16-1/8 IN LGTH, 1-5/8 IN DIA" },
  { category: "S Cam", partNumber: "PROWC513R", description: "RH 37 SPL 21-1/8 IN LGTH, 1-5/8 IN DIA" },

  { category: "Brake Drum and Brake Shoe", partNumber: "WEB77807BW", description: "NS ONLY - 16.5 X 7 VORTEX W/WEAR INDICATOR" },
  { category: "Brake Drum and Brake Shoe", partNumber: "WEB56864B", description: "DRUM 16.5 X 7" },
  { category: "Brake Drum and Brake Shoe", partNumber: "STEWK4515QCXLBL", description: "SHOE - B-LOCK W/KIT 4515W" },
  { category: "Brake Drum and Brake Shoe", partNumber: "PROBD16.5X7BMLI", description: "DCLI ONLY - 10 HOLE, UNIMNT 16-1/2 X 7-1/2" },
  { category: "Brake Drum and Brake Shoe", partNumber: "WEB57518F", description: "DCLI ONLY - DAYTON SPOKE 5/6HL, 6.5 X 7" },
  { category: "Brake Hardware Kit", partNumber: "PROWB047", description: "16-1/2 X 7 Q-PLUS MJR KIT" },

  { category: "Emergency Gladhand", partNumber: "PHI12-138", description: "RED EMER 38 DEG BOTTOM PORT" },
  { category: "Emergency Gladhand", partNumber: "PHI12-4908", description: "GLDHD RED (SPRING LOADED)" },
  { category: "Emergency Gladhand", partNumber: "PROGH-AL02", description: "RED/EMERGENCY SIDE STANDARD" },
  { category: "Emergency Gladhand", partNumber: "SLO441103", description: "RED SWINGAWAY, 45 DEGREE" },

  { category: "Twistlock Components", partNumber: "TWL-PT004", description: "REAR PIN LOW PRO, F33NS-LP" },
  { category: "Twistlock Components", partNumber: "TWL-PT103", description: "REAR PIN ML 85-2/3 W WASHER" },
  { category: "Twistlock Components", partNumber: "TWL-PT005", description: "REAR PIN 1257, 1259, 3229, 3248" },
  { category: "Twistlock Components", partNumber: "TWL-HD106", description: "DETENT BALL 3/8 440C STAINLESS ROUND" },
  { category: "Twistlock Components", partNumber: "TWL-PT037", description: "REAR 1148, 1235/36, 3270/9072" },
  { category: "Twistlock Components", partNumber: "TWL-PT009", description: "REAR DROP-IN TWL, PENZ 90-35-XXF L/R" },
  { category: "Twistlock Components", partNumber: "TWL-PT007", description: "REAR FOR NON RETRACTABLE" },
  { category: "Twistlock Components", partNumber: "TWL-PT184", description: "REAR PIN LOW PROFILE" },
  { category: "Twistlock Components", partNumber: "TWL-PT002", description: "REAR PIN 1131 1206 120773" },
  { category: "Twistlock Components", partNumber: "TWL-HD031", description: "GUIDE PLATE" },

  { category: "Under-Ride Guard Assembly", partNumber: "BMP-CC01", description: "DCLI, ORANGE, BOLT-ON, BOLTED ASSEMBLY" },
  { category: "Under-Ride Guard Assembly", partNumber: "BMP-CC11", description: "KIT CHEETAH" },
  { category: "Under-Ride Guard Assembly", partNumber: "BMP-HY02", description: "HYUN BOLT-ON KIT 94 IN, W/DIAG BRACE" },
  { category: "Under-Ride Guard Assembly", partNumber: "BMP-HY06", description: "KIT HYUNDAI, BOLT-ON, 94 IN" },
  { category: "Under-Ride Guard Assembly", partNumber: "BMP-HY10", description: "BUMPER ASSEMBLY (DCLI)" },
  { category: "Under-Ride Guard Assembly", partNumber: "BMP-ST12", description: "BUMPER ASSEMBLY STO, ICC, COMPLETE" },
  { category: "Under-Ride Guard Horizontal Tubular", partNumber: "BMP-ST10", description: "TUBE STO R28-03560-001-00" },
  { category: "Under-Ride Guard Horizontal Tubular", partNumber: "BMP-UN03V", description: "4 X 4 X 94 POOCHED 18-36-18 W/LABEL" },
  { category: "Under-Ride Guard Horizontal Tubular", partNumber: "BMP-UN04", description: "95 POOCHED TUBE 16-42-16 WELD ON W/LBL" },
  { category: "Under-Ride Guard Horizontal Bolt-On", partNumber: "BMP-CC07", description: "BUMPER TUBE CIMC CHASSIS" },
  { category: "Under-Ride Guard Horizontal Bolt-On", partNumber: "BMP-CC15", description: "TUBE CIMC BLACK CHASSIS NORFOLK" },
  { category: "Under-Ride Guard Horizontal Bolt-On", partNumber: "BMP-CC18", description: "DCLI TUBE CIMC, ORANGE, BOLT ON" },
  { category: "Under-Ride Guard Upright Bolt-On", partNumber: "BMP-CC02B", description: "CIMC BRACKET LEFT SIDE BLACK" },
  { category: "Under-Ride Guard Upright Bolt-On", partNumber: "BMP-CC03B", description: "CIMC BRACKET RIGHT SIDE BLACK" },

  { category: "7-Way Receptacle Base", partNumber: "PHI15-770", description: "ADAPT PLATE POWDER COATED 10GA STEEL" },
  { category: "7-Way Receptacle Base", partNumber: "PHI15-740", description: "SOCKET BOOT" },
  { category: "7-Way Receptacle Base", partNumber: "PHI15-769", description: "NOSE BOX KIT W/GASKET, 1-7/8 IN" },
  { category: "7-Way Receptacle", partNumber: "PHI15-720", description: "SOCKET, 7-WAY SPLIT PIN 2 HOLE MOUNT DIE-CAST SCREW T" },
  { category: "7-Way Receptacle", partNumber: "PHI16-722", description: "SOCKET STA NYLON 2 HOLE SPL PIN RING" },
  { category: "7-Way Receptacle", partNumber: "PHI16-720", description: "SOCKET STA DRY 2 HOLE SPLIT PIN, SCREW" },
  { category: "7-Way Receptacle", partNumber: "PHI16-724", description: "STADRY NYLON 2 HOLE SPL PIN BULLET T" },
  { category: "7-Way Receptacle", partNumber: "PHI15-730", description: "W/SPRG GUARD PLUG CONN DIE CAST" },
  { category: "7-Way Receptacle", partNumber: "PHI15-762", description: "W/SOCKET DIE CAST EXT BAR 20A" },
  { category: "7-Way Receptacle", partNumber: "PHI15-763", description: "W/SOCKET DIE CAST EXT BAR 30A" },
  { category: "7-Way Receptacle with Breaker", partNumber: "PHI15-760", description: "LRG SOCKET W/BREAKER STA-DRAY" },

  { category: "Mudflap", partNumber: "IMXGT-2424PSB", description: "24 X 24 3/16, POLY STD BLK" },
  { category: "Mudflap", partNumber: "IMXGT-2430PSB", description: "24 X 30 3/16, POLY STD BLACK" },
  { category: "Mudflap", partNumber: "SIRMFBK", description: "BOLT KIT 3/8 CARBON ZINC 4 BAG" },
  { category: "Mudflap Bracket", partNumber: "FLT033-00868", description: "FLAP BRKT SPRING LOADED, HD" },
  { category: "Mudflap Bracket", partNumber: "MUD-CC05", description: "BRACKET CHEETAH" },
  { category: "Mudflap Bracket", partNumber: "MUD-ST01", description: "BOLT-ON BRACKET 3/16 X 2 X 3 X 100-1/2" },
  { category: "Mudflap Bracket", partNumber: "MUD-UN01", description: "27.5 IN ANGLE, 10 GAUGE" },
  { category: "Mudflap Bracket", partNumber: "MUD-UN02", description: "RETAINING STRAP FOR BRACKET" }
];

if (typeof window !== "undefined") window.parts = parts;
if (typeof module !== "undefined") module.exports = parts;
